# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_ip', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=30)),
                ('s_b', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('remain', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(default=datetime.datetime(2016, 5, 28, 14, 54, 10, 260816, tzinfo=utc))),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
