# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 28, 14, 55, 35, 13951, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 14, 55, 35, 15677, tzinfo=utc)),
        ),
    ]
