# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160528_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
