# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160528_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
