# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160531_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order_id',
            new_name='order1_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='order2_id',
            field=models.IntegerField(default=0),
        ),
    ]
