# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_completedorder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completedorder',
            table='completed_order',
        ),
    ]
