# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160606_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderserver',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
