apiVersion: v1
kind: Service
metadata:
  name: broker-front
  labels:
    name: broker-front
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: nginx-broker
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-broker
    spec:
      containers:
      - name: nginx
        image: gcr.io/se350-project-3/broker-frontend-cluster2:v1
        ports:
        - containerPort: 80