apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: mysql
  name: mysql
spec: 
  ports:
    # the port that this service should serve on
    - port: 3306
      targetPort: 3306
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: mysql
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
          - containerPort: 3306
        volumeMounts:
          # name must match the volume name below
          - name: mysql-persistent-storage
          # mount path within the container
            mountPath: /var/lib/mysqltest1
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            # This GCE PD must already exist.
            pdName: mysql-disk-2
            fsType: ext4